### ISSUE TITLE
Try the "Allow auto-merge" setting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-metadata#1171]
I spotted a new setting in https://github.com/web-platform-tests/wpt-metadata/settings.

It links to https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request.

It's probably possible for the PRs to be created with this setting enabled, which would avoid the need for our current `automerge.yml`.

@KyleJu WDYT?

**Comment by KyleJu** [comment]
`If you allow auto-merge for pull requests in your repository, people with write permissions can configure individual pull requests in the repository to merge automatically when all merge requirements are met.`

Judging from the tutorial, auto-merge has to be [enabled for each PR individually](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request#enabling-auto-merge).  A little different from what we need now, which is auto-merge for all PRs unless using do-not-merge labels

**Comment by foolip** [comment]
Do we ever add the "do not merge" label for the automatic triage PRs? It not, then having those PRs be created with the auto merge setting would probably work, right?

**Comment by KyleJu** [comment]
> Do we ever add the "do not merge" label for the automatic triage PRs? It not, then having those PRs be created with the auto merge setting would probably work, right?

IIUC, we set the permission to allow them to auto-merge on the repository. But each user has to enable it for each PR

**Comment by KyleJu** [comment]
Jus tested it with https://github.com/web-platform-tests/wpt-metadata/pull/1173. Users have to **manually** enable auto-merge for **each** PR. I think the use

**Comment by foolip** [comment]
I was thinking of having the bot-created PRs getting this enabled by the bots creating the PRs. But maybe automatically merging PRs created by humans is also important?

And I see there's also a Gecko not so this would require a bit too much work to be worth it.

**Comment by KyleJu** [comment]
> I was thinking of having the bot-created PRs getting this enabled by the bots creating the PRs. But maybe automatically merging PRs created by humans is also important?
> 
> And I see there's also a Gecko not so this would require a bit too much work to be worth it.

I see. But right we have to ask the Gecko bot/authors to make a similar change. Changes to META.yml files should be auto merged regardless of authors

**Comment by foolip** [comment]
Closing this, things are working :)
