### ISSUE TITLE
GitHub checks not running update_wpt_manifest.yml

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#1444]
https://github.com/web-platform-tests/wpt-metadata/pull/1441. After creation, the GitHub checks are stuck and didn't run properly. I have to close and open again to trigger the checks.

It occurs for all the PRs created by https://github.com/web-platform-tests/wpt-metadata/blob/master/.github/workflows/update_wpt_manifest.yml

**Comment by KyleJu** [comment]
Looks like it is a known issue https://github.com/peter-evans/create-pull-request/issues/48

**Comment by foolip** [comment]
We can fix this by adding a token as a secret that we use only for creating the PR. Unfortunately, the user behind that token would then be the owner of the PR, instead of github-actions.

**Comment by foolip** [comment]
The effect of this is that human intervention is always required to update the manifest. It looks like this might be the cause of https://github.com/web-platform-tests/wpt-metadata/issues/3480.

@past until this is fixed, do you think we can add this to the rotation. Also cc @jcscottiii

**Comment by foolip** [comment]
Looks like the issue also affects "Resolve pending metadata" PRs, like https://github.com/web-platform-tests/wpt-metadata/pull/3457.

**Comment by jcscottiii** [comment]
There's a new [workaround](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs) that we should do:

> Use a [machine account that creates pull requests from its own fork](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#push-pull-request-branches-to-a-fork). This is the most secure because the PAT created only grants access to the machine account's fork, not the main repository. This method will trigger on: pull_request workflows to run. Workflows triggered on: push will not run because the push event is in the fork.

All of the affected actions use are triggered by `on: pull_request` so it should work.

**Comment by foolip** [comment]
Yeah, that sounds like it would work!
