### ISSUE TITLE
Support auto-merge for moz-wptsync-bot 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#172]
The `MERGE_FILTER_AUTHOR` in the https://github.com/pascalgn/automerge-action workflow only supports one author at the moment. To support `moz-wptsync-bot`,  we can remove `MERGE_FILTER_AUTHOR` and use `MERGE_LABELS` to identify auto-merge PR candidates. I propose labels `mozilla:gecko-sync` and `wpt.fyi:auto-merge` for `moz-wptsync-bot` and `wptfyibot`

**Comment by stephenmcgruer** [comment]
Could we find a different action that supports two authors?

**Comment by KyleJu** [comment]
> Could we find a different action that supports two authors?

Well, we identified two candidates for the automerge workflow, the one in use and [autosquash](https://github.com/tibdex/autosquash), based on how widely it is used and how frequent it is maintained. None of them supports multiple authors, and the rest of choices is rarely used by other people. I think I will go ahead with @Hexcles' suggestions per our offline discussions

**Comment by stephenmcgruer** [comment]
> I think I will go ahead with @Hexcles' suggestions per our offline discussions

Sounds good; can you document them here for the rest of us? :)

**Comment by KyleJu** [comment]
Per @Hexcles' suggestions, we will auto-merge all files, regardless of authors. If there are files we should not be automatically merged, e.g. testing or GitHub checks, it won't do so as long as a `do not merge yet` label is present in PRs. We will enforce a review on non META.yml FILES by adding them to the CODEOWNERS.

**Comment by stephenmcgruer** [comment]
> auto-merge all files, regardless of authors

Except from forks, I presume?

**Comment by KyleJu** [comment]
> > auto-merge all files, regardless of authors
> 
> Except from forks, I presume?

Oops I missed it. That's correct

**Comment by KyleJu** [comment]
I just realized that to enable `Require review from Code Owners`, I have to enable `Require pull request reviews` (which disables auto-merge). Let me find a way around it.

**Comment by Hexcles** [comment]
I'm going to play the devil's advocate: let's add an auto-approve action to approve everything and turn on branch protection https://github.com/hmarr/auto-approve-action

**Comment by KyleJu** [comment]
> I'm going to play the devil's advocate: let's add an auto-approve action to approve everything and turn on branch protection https://github.com/hmarr/auto-approve-action

I was thinking that a pull request template could help remind people to add `do not merge yet` labels, but what you suggested leaves less room for mistakes and also enforces CODEOWNERS

**Comment by Hexcles** [comment]
> I was thinking that a pull request template could help remind people to add do not merge yet labels

We could still do that, which might be more friendly / obvious to human contributors. Just need to make sure that the template won't get applied to the automatically created PRs, too.

**Comment by KyleJu** [comment]
This issue was closed by github actions bot by mistake
