### ISSUE TITLE
Travis is saying that tests in workers/interfaces.worker.html no longer exists and is causing tests to fail

### ISSUE THREAD

**Issue by AutomatedTester** [web-platform-tests/wpt-metadata#32]
```
--- FAIL: TestResultsTestPaths/Manifest_@_a12f37b/workers (0.00s)

            --- FAIL: TestResultsTestPaths/Manifest_@_a12f37b/workers/workers/interfaces.worker.html (0.00s)

                test_paths_test.go:102: 

                    	Error Trace:	test_paths_test.go:102

                    	Error:      	Should be true

                    	Test:       	TestResultsTestPaths/Manifest_@_a12f37b/workers/workers/interfaces.worker.html

                    	Messages:   	workers/interfaces.worker.html is not a test path found in the manifest @ a12f37b
```

**Comment by AutomatedTester** [comment]
This appears to be down to the idlharness magic. Yes the file doesn't exist in the tree but it is reported when there are failures.

**Comment by lukebjerring** [comment]
https://wpt.fyi/results/workers doesn't show any results for interfaces.worker.html. 
Note that the test verifies paths resolved as their reported test names, not file names, so the exploding name magic is accounted for.
`git log --full-history  -- workers/interfaces.worker.js` showed it was deleted here
https://github.com/web-platform-tests/wpt/pull/18690/files#diff-0f0cfd91cc1524859d81b4bcdb65160d
