### ISSUE TITLE
Lots of open pull requests with failing tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-metadata#3480]
https://github.com/web-platform-tests/wpt-metadata/pulls shows many open "Automatically Triage New Metadata" PRs right now with failing tests.

@jcscottiii it looks like @KyleJu is OOO, so can you help take a look at this?

The first thing I'd check is https://github.com/web-platform-tests/wpt-metadata/pull/3417, which is stuck since two weeks. When we don't update the manifest, PRs start failing because the paths don't exist yet.

**Comment by foolip** [comment]
I've merged https://github.com/web-platform-tests/wpt-metadata/pull/3417 so now the remaining work is to go through and make sure all of the backed up PRs get merged.

**Comment by foolip** [comment]
Thanks @jcscottiii, that's great!

**Comment by KyleJu** [comment]
Thanks @jcscottiii !
