### ISSUE TITLE
Don't automatically approve/merge changes to interop-* labels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-metadata#3954]
In https://github.com/web-platform-tests/interop/pull/288 I've created a workflow to ensure that there aren't unexpected changes to the set of tests in Interop 2023 and previous efforts.

@jgraham suggested that we instead prevent unexpected changes at the source, before they happen. We could do this by not approving or merging PRs to this repo if it changes the set of tests with an interop-* label, possibly excluding renames created by automated workflows.

@KyleJu do you think implementing this would be straightforward? Is there any CI step currently that compares the state of the repo before and after the change?

**Comment by KyleJu** [comment]
Added it to the backlog and hope to address it in Q2

**Comment by foolip** [comment]
Thanks Kyle!

**Comment by WeizhongX** [comment]
foolip@, I assume this will not have an impact to the exporter because we only meant to not auto merge to interop-* label?

**Comment by foolip** [comment]
@WeizhongX right this will not affect import/export for the wpt repo.

**Comment by DanielRyanSmith** [comment]
I've looked into this a bit today, and this might not be a simple change to implement through GitHub Actions alone via our current auto-approver. Flagging a PR that is making changes to an interop label is actually pretty complex based on the current structure of how metadata changes are stored. 

In terms of flagging PRs for non-auto approval at the simple GH Actions level, we would need to create logic to discern PRs updating interop labels from [this contextual information](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), which I'm not sure is possible.

As it stands, these factors are what is making this difficult:
- Interop labels can be changed can be in almost any file, so we can't just flag changes on a specific file.
- PR change diffs can make changes to interop labels without specifically editing a line that has text that signals a change to said interop labels. I don't know if we can specifically parse diffs in GH Actions, but doing so would likely not be fruitful to begin with.

I'm not certain the best approach here if it is the case that we cannot discern interop label changes from the GH Action context information. It might be possible to solve this issue by creating a script that aggregates interop label information and run it for each new PR, comparing it with results from the script when run on the main branch. Even then, I am uncertain of the best way to compare these results.

This is just an initial thought, and I wouldn't be surprised if I've missed something that would be useful to handle this issue.
