### ISSUE TITLE
Create a cron job to detect/modify renaming and deletion

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#41]
Create a cron job to detect/modify renaming and deletion, shown in the follow-up [section](https://docs.google.com/document/d/1oWYVkc2ztANCGUxwNVTQHlWV32zq6Ifq9jkkbYNbSAg/edit?ts=5d0a7f5c#heading=h.wha35vi2ktvy)

**Comment by stephenmcgruer** [comment]
I'm not familiar with the extent of Github Actions power; could we have an on-merge action in wpt which does this, rather than a daily cronjob? (cc @Hexcles )

**Comment by Hexcles** [comment]
Yes a GitHub Action on merge is possible. Even if we want to use a cron job instead for whatever reasons (e.g. capacity), it would be a GitHub Action as well.

**Comment by foolip** [comment]
Push to master would be the thing to trigger on, like the documentation and manifest build workflows.

**Comment by KyleJu** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/171

**Comment by KyleJu** [comment]
Possibly bumping the priority of this bug for Q4 since the GitHub breakages has been quite frequent (due to the increasing usage of the wpt-metadata repo).  Some summaries from the offline discussions

Stephen: "Note that detecting renames is a non-trivial task in general, e.g. see crbug.com/1141061 which is an unrelated case for the importer where rename detection is causing problems"

Addressing pure renaming cases might be a good start since there is no renaming detection at the moment. I have seen more complicated cases where tests are being divided/combined, and as a result the matching between tests and bug URLs are totally off, although the same test names still exist under the same test directories.

**Comment by foolip** [comment]
Should this really be closed? Will renaming a test in WPT which has metadata now result in a rename in this repo?

**Comment by KyleJu** [comment]
Interesting, this was closed automatically
