### ISSUE TITLE
Possibility to mark paths (whole directories) ?

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt-metadata#49]
With the current format for wpt.fyi metadata I don't see how I can tag a whole directory to a specific product bug.

For example, I would like to tag ```css/motion/*``` for Safari to URL https://bugs.webkit.org/show_bug.cgi?id=139127

Is there any way other than individually listing the (many) tests inside ```css/motion/*``` ?

//cc @stephenmcgruer @foolip

**Comment by KyleJu** [comment]
@clopez Sorry for the wait. I have enabled the support for `*` in wpt-metadata. A link with `test` as `*` will apply to all tests in the current directory and its sub-directories.

**Comment by KyleJu** [comment]
Let me know if you have questions. Will close this bug at the same time.

**Comment by clopez** [comment]
Thanks! :)
