### ISSUE TITLE
"Automatically Triage New Metadata" PRs not being merged

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-metadata#5473]
See sts/wpt-metadata/pulls.

I've had to merge a lot of PRs manually today, and resolve conflicts for many.

**Comment by foolip** [comment]
@valenting FYI, a bunch of your PRs are stuck because of this. I've merged some, but not all of them yet.

**Comment by valenting** [comment]
@foolip Thanks for the heads-up. Do you know if this was because of the PR volume (I've triaged a lot of URL failures in the past few days) or some other issue?

**Comment by foolip** [comment]
@valenting You should be able to triage as fast as you can go, and I don't think it's because of the volume. There's code in place to resolve conflicts if they happen, and generally people shouldn't need to know that the metadata is stored in this repo, it should just work.

I'm not sure about the cause yet, but I think it's either because https://github.com/web-platform-tests/wpt-metadata/pull/5371 hasn't landed to resolve conflicts, or https://github.com/web-platform-tests/wpt-metadata/actions/workflows/automerge.yml is broken in general.

**Comment by jcscottiii** [comment]
Quick glance at stuck PR #5402

It was created at 2024-01-10T16:45:52Z

However taking a look at PR #5401, which was automerged, shows it was created at 2024-01-10T16:44:57Z

- PR 5401's automerge GitHub logs: https://github.com/web-platform-tests/wpt-metadata/actions/runs/7478098626/job/20352283128

- PR 5402's automerge GitHub logs: https://github.com/web-platform-tests/wpt-metadata/actions/runs/7478110263/job/20352323480
  - Shows:
  ```
  2024-01-10T16:47:13.145Z INFO  Parsing PULL_REQUEST input: 5402
  2024-01-10T16:47:13.148Z INFO  Event name: workflow_dispatch
  2024-01-10T16:47:13.149Z INFO  Looking for pull request #5402...
  2024-01-10T16:47:[13](https://github.com/web-platform-tests/wpt-metadata/actions/runs/7478110263/job/20352323480#step:2:14).472Z INFO  Skipping PR update, required label missing: automerge
  2024-01-10T16:47:13.472Z INFO  Merging PR #5402 Automatically Triage New Metadata
  2024-01-10T16:47:13.472Z INFO  PR not ready: mergeable_state: dirty
  2024-01-10T[16](https://github.com/web-platform-tests/wpt-metadata/actions/runs/7478110263/job/20352323480#step:2:17):47:13.473Z INFO  Action result: { mergeResult: 'not_ready', pullRequestNumber: 5402 }
  ```
  
 I searched for `dirty` in the GitHub docs. In the [docs](https://docs.github.com/en/graphql/reference/enums#mergestatestatus) it saw there was a conflict when trying to make a merge commit for 5402

**Comment by foolip** [comment]
> I am inclined to say that there exists a minimum time N before another triage can be made to the same file.

Although I'm not familiar with the details, I think PRs like https://github.com/web-platform-tests/wpt-metadata/pull/5371 are created to handle cases like this. From memory, changes that remain in wpt.fyi's cached representation of metadata are recreated, effectively resolving conflicts by recreating the change. @KyleJu is that right?

Of course, if the exact same piece of data is being edited over and over no system can resolve those conflicts, but I don't think that's happening here.

I'll stop manually merging PRs now so that the investigation can proceed.

**Comment by jcscottiii** [comment]
You are correct that PRs like #5371 are created to resolve this. This daily GitHub action [generates](https://github.com/web-platform-tests/wpt-metadata/blob/master/.github/workflows/resolve_merge_conflict.yml) it. That PR will not be auto merged (on purpose). Once someone reviews it, they can merge it and close out all the pending "Automatically Triage New Metadata" PRs which have conflicts

**Comment by foolip** [comment]
Oh, I didn't realize that requires review... It would be great to document how to handle these PRs. I presume one has to be careful to only close PRs that are older than the "Resolve pending metadata" PR, but what are the precise rules?

**Comment by jcscottiii** [comment]
Documenting that is a great idea.

Luckily, when the daily job runs (or when we trigger an [ad-hoc run](https://github.com/web-platform-tests/wpt-metadata/actions/workflows/resolve_merge_conflict.yml)), it will re-generate the PR to resolve the conflicts for the new list of outstanding PRs.

**Comment by jcscottiii** [comment]
@KyleJu Quick question, is there a reason why auto merging was disabled for the resolve conflict PRs?

**Comment by KyleJu** [comment]
> @KyleJu Quick question, is there a reason why auto merging was disabled for the resolve conflict PRs (besides having to clean up the PRs that have conflicts afterwards)?

Auto-merge should be enabled for the resolve conflict PRs. I think we just didn't get around it after you made a change to auto-approve it. Another issue is that GitHub actions are occasionally stuck in the queue, without no results reporting back to the CI, e.g.

<img width="998" alt="Screenshot 2024-01-12 at 12 59 17 PM (2)" src="https://github.com/web-platform-tests/wpt-metadata/assets/8611520/432c5391-73c3-4c6f-9546-d95d741fa54a">

I will have to look into it. Let me send out a PR to enable auto-merge first.

**Comment by KyleJu** [comment]
Auto-merged is enabled, https://github.com/web-platform-tests/wpt-metadata/pull/5488

**Comment by foolip** [comment]
Thanks @KyleJu and @jcscottiii!
