### ISSUE TITLE
[GitHub Checks] Increasing GitHub checks failure rate

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#639]
Due to the increasing usage, GitHub checks have been failing >2 a week. We have to rethink the model as it has required greater maintenance effort. The painpoints are caused by

- merge conflict, when multiple PRs triage the same files and the order of metadata entries change
- checks are blocked when unrelated tests are renamed, etc (only run tests on the PR changes).

Per various offline discussions, the first issue can be improved by sorting the metadata entries but not completely eliminated. To fix the second issue, we first need a reliable cron job to detect renaming/deletion before we unblock the check, because renaming/deletion will go undetected and require greater cleanup effort over time.

**Comment by foolip** [comment]
For merge conflicts, there's also the option of keeping the original request ("link this to that") around until it can be applied, and to reapply it whenever there are conflicts. I'm guessing that most merge conflicts are textual and would not be conflicting changes in an in-memory representation.

**Comment by foolip** [comment]
Is this still going to happen as much with the in-memory model?

**Comment by KyleJu** [comment]
> For merge conflicts, there's also the option of keeping the original request ("link this to that") around until it can be applied, and to reapply it whenever there are conflicts. I'm guessing that most merge conflicts are textual and would not be conflicting changes in an in-memory representation.

Yes, merge conflicts will be fixed by https://github.com/web-platform-tests/wpt-metadata/pull/1139 and im planning to tackle the renaming through this GitHub action as well

**Comment by foolip** [comment]
For the renaming, we could ensure that never causes CI checks to fail by pinning a specific version of WPT (or a MANIFEST.json built from it) and checking test paths against that.

Then a scheduled job could update the pinned version and try to rename. Human intervention would only be needed if the rename detection fails for some reason.

**Comment by KyleJu** [comment]
> For the renaming, we could ensure that never causes CI checks to fail by pinning a specific version of WPT (or a MANIFEST.json built from it) and checking test paths against that.
> 
> Then a scheduled job could update the pinned version and try to rename. Human intervention would only be needed if the rename detection fails for some reason.

Yea thats a good idea. We can store `sha` used in [api/manifest](https://github.com/web-platform-tests/wpt.fyi/tree/main/api#apimanifest) in a text file somewhere and update the text file
