### ISSUE TITLE
Wrong Test Localtion in wpt-metadata/WebIDL/META.yml 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#66]
https://github.com/web-platform-tests/wpt-metadata/blob/master/WebIDL/META.yml#L5 is on the wrong directory. It should be parallel to https://github.com/web-platform-tests/wpt/tree/master/WebIDL/ecmascript-binding directory.

A check for it needs to added in the test

**Comment by stephenmcgruer** [comment]
Is this fixed? The META.yml appears to be at https://github.com/web-platform-tests/wpt-metadata/blob/master/WebIDL/ecmascript-binding/META.yml now?

**Comment by KyleJu** [comment]
There is a [check](https://github.com/web-platform-tests/wpt-metadata/blob/master/parse_test.go#L54) for this problem already. I will this issue.
