### ISSUE TITLE
GitHub Check Failing on Master - cannot unmarshal Manifest into Go struct

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#80]
See [failure message](https://github.com/web-platform-tests/wpt-metadata/pull/79/checks?check_run_id=420088483). Test is [failing](https://github.com/web-platform-tests/wpt-metadata/blob/master/test_paths_test.go#L48) when trying to unmarshall data from https://wpt.fyi/api/manifest?sha=latest

**Comment by KyleJu** [comment]
https://github.com/web-platform-tests/wpt/pull/16537

**Comment by Hexcles** [comment]
Also filed https://github.com/web-platform-tests/wpt.fyi/issues/1777

Once I fixed that, this issue should be resolved automatically.

BTW, I wasn't aware that `wpt-metadata` needed the manifest. What's it for?

**Comment by KyleJu** [comment]
It is used to verify if YML files and tests are in the correct file directories
